import * as React from 'react';
import './globals.css';
import Providers from '@/providers';
import Dashboard from '../DefaultLayout';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout(props: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Dashboard>{props.children}</Dashboard>
        </Providers>
      </body>
    </html>
  );
}
